//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCheckState
    {
        public string WebsiteId { get; set; }
        public string ServerId { get; set; }
        public bool IsCompleted { get; set; }
        public string Fields { get; set; }
    }
}
