//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiniProfilerSqlTiming
    {
        public int RowId { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid MiniProfilerId { get; set; }
        public System.Guid ParentTimingId { get; set; }
        public byte ExecuteType { get; set; }
        public decimal StartMilliseconds { get; set; }
        public decimal DurationMilliseconds { get; set; }
        public Nullable<decimal> FirstFetchDurationMilliseconds { get; set; }
        public bool IsDuplicate { get; set; }
        public string StackTraceSnippet { get; set; }
        public string CommandString { get; set; }
    }
}
