//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiniProfilerSqlTimingParameter
    {
        public int RowId { get; set; }
        public System.Guid MiniProfilerId { get; set; }
        public System.Guid ParentSqlTimingId { get; set; }
        public string Name { get; set; }
        public string DbType { get; set; }
        public Nullable<int> Size { get; set; }
        public string Value { get; set; }
    }
}
