//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransactionInfo
    {
        public string Id { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string WebsiteId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Fields { get; set; }
        public Nullable<System.Guid> PaymentMethodId { get; set; }
        public string PaymentStatus { get; set; }
    }
}
