//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public System.Guid Id { get; set; }
        public string WebsiteId { get; set; }
        public string Name { get; set; }
        public string PaymentModuleId { get; set; }
        public int SortNo { get; set; }
        public bool IsDefault { get; set; }
        public string ImagePath { get; set; }
        public bool Active { get; set; }
        public string Fields { get; set; }
    }
}
