//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public System.Guid Id { get; set; }
        public string ProductId { get; set; }
        public int Rating { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public string StatusId { get; set; }
        public System.DateTime Date { get; set; }
        public string WebsiteId { get; set; }
        public string ProductTitle { get; set; }
    
        public virtual Website Website { get; set; }
    }
}
