//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public System.Guid Id { get; set; }
        public string ProductId { get; set; }
        public string VariantId { get; set; }
        public int OrderNo { get; set; }
        public string Image { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
