//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanaText
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string GroupCode { get; set; }
        public string WebsiteId { get; set; }
        public int LanguageId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Fields { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Website Website { get; set; }
    }
}
