//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingMethod
    {
        public System.Guid Id { get; set; }
        public string ProviderType { get; set; }
        public string WebsiteId { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public string ImagePath { get; set; }
        public string Fields { get; set; }
        public int SortNo { get; set; }
        public string ExternalShippingMethodId { get; set; }
    
        public virtual Website Website { get; set; }
    }
}
