//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockRanx
    {
        public System.Guid Id { get; set; }
        public string WebsiteId { get; set; }
        public string CategoryId { get; set; }
        public int OutOfStock { get; set; }
        public int LowStock { get; set; }
    }
}
