//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteErpStatus
    {
        public string WebsiteId { get; set; }
        public bool IsOnline { get; set; }
        public int ConnectionErrorsCount { get; set; }
        public string Fields { get; set; }
    }
}
