//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteDomain
    {
        public System.Guid Id { get; set; }
        public string WebsiteId { get; set; }
        public string Domain { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<int> LanguageId { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Website Website { get; set; }
        public virtual WebsiteDomain WebsiteDomains1 { get; set; }
        public virtual WebsiteDomain WebsiteDomain1 { get; set; }
    }
}
